[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerServiceAccount")]
class MSFT_xSQLServerServiceAccount : OMI_BaseResource
{
    [Key, Description("Hostname of the SQL Server.")] String SQLServer;
    [Key, Description("Name of the SQL instance.")] String SQLInstanceName;
    [Key, Description("Type of service being managed."), ValueMap {"SqlServer","SqlAgent","Search","SqlServerIntegrationService","AnalysisServer","ReportServer","SqlBrowser","NotificationServer"}, Values {"SqlServer","SqlAgent","Search","SqlServerIntegrationService","AnalysisServer","ReportServer","SqlBrowser","NotificationServer"}] String ServiceType;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("The service account that should be used when running the service.")] String ServiceAccount;
    [Write, Description("Determines whether the service is automatically restarted.")] Boolean RestartService;
    [Write, Description("Forces the service account to be updated. Useful for password changes.")] Boolean Force;
};
