
[ClassVersion("1.0.0.0"), FriendlyName("SqlSecureConnection")]
class DSC_SqlSecureConnection : OMI_BaseResource
{
    [Key, Description("Name of the SQL Server instance to be configured.")] String InstanceName;
    [Required, Description("Thumbprint of the certificate being used for encryption. If parameter Ensure is set to 'Absent' then the parameter Certificate can be set to an empty string.")] String Thumbprint;
    [Write, Description("If all connections to the SQL instance should be encrypted. If this parameter is not assigned a value, the default is, set to true, that all connections must be encrypted.")] boolean ForceEncryption;
    [Required, Description("Name of the account running the SQL Server service. If parameter is set to 'LocalSystem', then a connection error is displayed. Use 'SYSTEM' instead, in that case.")] String ServiceAccount;
    [Write, Description("If set to $true then the required restart will be suppressed. You will need to restart the service before changes will take effect. The default value is $false.")] Boolean SuppressRestart;
    [Write, Description("If Encryption should be Enabled (Present) or Disabled (Absent)."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

