[ClassVersion("1.0.0.0"), FriendlyName("SqlAgentAlert")]
class DSC_SqlAgentAlert : OMI_BaseResource
{
    [Key, Description("The name of the SQL Agent Alert.")] String Name;
    [Write, Description("Specifies if the SQL Agent Alert should be present or absent. Default is Present."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The host name of the SQL Server to be configured. Default is $env:COMPUTERNAME.")] String ServerName;
    [Key, Description("The name of the SQL instance to be configured.")] String InstanceName;
    [Write, Description("The severity of the SQL Agent Alert.")] String Severity;
    [Write, Description("The message id of the SQL Agent Alert.")] String MessageId;
};
