# https://github.com/microsoft/PullRequestQuantifier/blob/main/docs/prquantifier-yaml.md
Excluded:
- '*.md'
Thresholds:
- Value: 50
  Label: PR extra small
  Color: Green
- Value: 100
  Label: PR small
  Color: Green
- Value: 200
  Label: PR medium
  Color: Yellow
- Value: 400
  Label: PR large
  Color: DarkYellow
- Value: 1000
  Label: PR extra large
  Color: Red
IgnoreRenamed: true
