[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerMaxDop")]
class MSFT_xSQLServerMaxDop : OMI_BaseResource
{
    [Write, Description("An enumerated value that describes if MaxDop is configured (Present) or reset to default value (Absent)"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Flag to Dynamically allocate Maxdop based on Best Practices")] Boolean DynamicAlloc;
    [Write, Description("Numeric value to configure Maxdop to")] Sint32 MaxDop;
    [Write, Description("The host name of the SQL Server to be configured. Default value is '$env:COMPUTERNAME'.")] String SQLServer;
    [Key, Description("The name of the SQL instance to be configured.")] String SQLInstanceName;
};
