---
####################################################
#          ModuleBuilder Configuration             #
####################################################
# Path to the Module Manifest to build (where path will be resolved from)
# SourcePath: ./Sampler/Sampler.psd1
# Output Directory where ModuleBuilder will build the Module, relative to module manifest
# OutputDirectory: ../output/Sampler
CopyDirectories:
  - DSCResources
  - en-US
# SemVer: '1.2.3'
# Suffix to add to Root module PSM1 after merge (here, the Set-Alias exporting IB tasks)
# suffix: suffix.ps1
VersionedOutputDirectory: true

####################################################
#      ModuleBuilder Submodules Configuration      #
####################################################

NestedModule:
  SqlServerDsc.Common:
    Path: ./src/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1
    OutputDirectory: ./output/SqlServerDsc/$ModuleVersionFolder/Modules/SqlServerDsc.Common
    VersionedOutputDirectory: false

####################################################
#       Sampler Pipeline Configuration             #
####################################################
# Defining 'Workflows' (suite of InvkeBuild tasks) to be run using their alias
BuildWorkflow:
  '.': # "." is the default Invoke-Build workflow. It is called when no -Tasks is specified to the build.ps1
    - build
    - test

  build:
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder
    - Create_changelog_release_output

  pack:
    - build
    - package_module_nupkg

  # defining test task to be run when invoking `./build.ps1 -Tasks test`
  test:
    - Pester_Tests_Stop_On_Fail
    - Pester_if_Code_Coverage_Under_Threshold

  publish:
    - Publish_release_to_GitHub
    - publish_module_to_gallery # runs if nuget is not available


####################################################
#       PESTER  Configuration                      #
####################################################

Pester: #Passthru, OutputFile, CodeCoverageOutputFile not supported
  OutputFormat: NUnitXML
  # Will look at every *.ps1 & *.psm1 under ModulePath, excepts when $_.FullName -match (Join-Path $ProjectPath $ExcludeFromCodeCoverageItem)
  ExcludeFromCodeCoverage:
    - tasks
    - Template
  # Default is to use the tests folder in the project folder or source folder (if present)
  # can use it to prioritize: tests/QA, tests/Unit, tests/Integration
  Script:
  # - tests/QA/module.tests.ps1
  # - tests/QA
  # - tests/Unit
  # - tests/Integration
  ExcludeTag:
  Tag:
  CodeCoverageThreshold: 50 # Set to 0 to bypass


Resolve-Dependency: #Parameters for Resolve-Dependency
  #PSDependTarget: ./output/modules
  #Proxy: ''
  #ProxyCredential:
  Gallery: 'PSGallery'
  # AllowOldPowerShellGetModule: true
  #MinimumPSDependVersion = '0.3.0'
  AllowPrerelease: false
  Verbose: false

ModuleBuildTasks:
  # - ModuleName: 'alias to search'
  Sampler:
    - '*.build.Sampler.ib.tasks' # this means: import (dot source) all aliases ending with .ib.tasks exported by sampler module

# Invoke-Build Header to be used to 'decorate' the terminal output of the tasks.
TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

GitHubConfig:
  GitHubFilesToAdd:
    - 'CHANGELOG.md'
  GitHubConfigUserName: gaelcolas
  GitHubConfigUserEmail: gaelcolas@synedgy.com
  UpdateChangelogOnPrerelease: false
