---
####################################################
#          ModuleBuilder Configuration             #
####################################################
CopyPaths:
  - DSCResources
  - en-US
  - Modules
Encoding: UTF8
VersionedOutputDirectory: true

ModuleBuildTasks:
  Sampler:
    - '*.build.Sampler.ib.tasks'
  DscResource.DocGenerator:
    - 'Task.*'

TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

####################################################
#   ModuleBuilder Dependent Modules Configuration  #
####################################################
NestedModule:
  DscResource.Common:
    CopyOnly: true
    Path: ./output/RequiredModules/DscResource.Common
    AddToManifest: false
    Exclude: PSGetModuleInfo.xml

####################################################
#           Pipeline Configuration                 #
####################################################
BuildWorkflow:
  '.':
    - build
    - test

  build:
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder
    - Create_Changelog_Release_Output
    - Generate_Conceptual_Help
    - Generate_Wiki_Content

  pack:
    - build
    - package_module_nupkg

  hqrmtest:
    - DscResource_Tests_Stop_On_Fail

  test:
    - Pester_Tests_Stop_On_Fail
    - Pester_If_Code_Coverage_Under_Threshold

  publish:
    - Publish_Release_To_GitHub
    - Publish_Module_To_gallery
    - Publish_GitHub_Wiki_Content

####################################################
#              PESTER Configuration                #
####################################################
Pester:
  OutputFormat: NUnitXML
  ExcludeFromCodeCoverage:
    - Modules/DscResource.Common
    # Deprecated resources
    - source/DSCResources/MSFT_SqlServerNetwork
    - source/DSCResources/MSFT_SqlDatabaseOwner
    - source/DSCResources/MSFT_SqlDatabaseRecoveryModel
    - source/DSCResources/MSFT_SqlServerEndpointState
  Script:
    - tests/Unit
  ExcludeTag:
  Tag:
  CodeCoverageThreshold: 85
  CodeCoverageOutputFile: JaCoCo_coverage.xml
  CodeCoverageOutputFileEncoding: ascii

DscTest:
  ExcludeTag:
    - "Common Tests - New Error-Level Script Analyzer Rules"
  Tag:
  ExcludeSourceFile:
    - output
    # Deprecated resources
    - source/DSCResources/MSFT_SqlServerNetwork
    - source/DSCResources/MSFT_SqlDatabaseOwner
    - source/DSCResources/MSFT_SqlDatabaseRecoveryModel
    - source/DSCResources/MSFT_SqlServerEndpointState
  ExcludeModuleFile:
    - Modules/DscResource.Common
    # Deprecated resources
    - DSCResources/MSFT_SqlServerNetwork
    - DSCResources/MSFT_SqlDatabaseOwner
    - DSCResources/MSFT_SqlDatabaseRecoveryModel
    - DSCResources/MSFT_SqlServerEndpointState

####################################################
#              PSDepend Configuration              #
####################################################
Resolve-Dependency:
  Gallery: 'PSGallery'
  AllowPrerelease: false
  Verbose: false

####################################################
#               GitHub Configuration               #
####################################################
GitHubConfig:
  GitHubFilesToAdd:
    - 'CHANGELOG.md'
  GitHubConfigUserName: dscbot
  GitHubConfigUserEmail: dsccommunity@outlook.com
  UpdateChangelogOnPrerelease: false

####################################################
#      DscResource.DocGenerator Configuration      #
####################################################
DscResource.DocGenerator:
  Generate_Conceptual_Help:
    MarkdownCodeRegularExpression:
      - '\`(.+?)\`' # Match inline code-block
      - '\\(\\)' # Match escaped backslash
      - '\[[^\[]+\]\((.+?)\)' # Match markdown URL
      - '_(.+?)_' # Match Italic (underscore)
      - '\*\*(.+?)\*\*' # Match bold
      - '\*(.+?)\*' # Match Italic (asterisk)
