codecov:
  require_ci_to_pass: no
  # main should be the baseline for reporting
  branch: main

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  show_carryforward_flags: true

coverage:
  range: 50..80
  round: down
  precision: 0

  status:
    project:
      default:
        # Set the overall project code coverage requirement to 70%
        target: 70
        flags:
          - unit
    patch:
      default:
        # Set the pull request requirement to not regress overall coverage by more than 5%
        # and let codecov.io set the goal for the code changed in the patch.
        target: auto
        threshold: 5
        flags:
          - unit
flags:
  unit:
    paths:
      - source/
    carryforward: true

fixes:
  - '^\d+\.\d+\.\d+::source'  # move path "X.Y.Z" => "source"
