ConvertFrom-StringData @'
    RetrievingAuditInfo = Retrieving information about Audit '{0}' from the server '{1}'. (SSA0001)
    AuditNotFound = The audit '{0}' does not exist. (SSA0002)
    EvaluateAudit = Determining if the audit '{0}' on server '{1}' instance '{2}' is in the desired state. (SSA0003)
    AuditExist = The audit '{0}' exist in on server '{1}'. (SSA0004)
    AuditDoesNotExist = The audit '{0}' does not exist on server '{1}'. (SSA0005)
    InDesiredState = The audit is in desired state. (SSA0006)
    NotInDesiredState = The audit is not in desired state. (SSA0007)
    UnknownAuditType = The databaser user has an, by the resource, unsupported combination of authentication type '{0}' and login type '{1}'. (SSA0008)
    CreateAudit = Creating the audit '{0}' on server '{1}' instance '{2}'. (SSA0009)
	FailedCreateAudit = Failed creating audit '{0}' on server '{1}' instance '{2}'. (SSA0010)
    DropAudit = Removing the audit '{0}' from server '{1}' instance '{2}'. (SSA0011)
	FailedDropAudit = Failed removing the audit '{0}' from server '{1}' instance '{2}'. (SSA0012)
    SetAudit = Setting the audit '{0}' on server '{1}' instance '{2}' to the desired state. (SSA0013)
	FailedUpdateAudit = Failed updating audit '{0}' on server '{1}' instance '{2}'. (SSA0014)
    ChangingAuditFilePath = Changing audit '{0}' to use this filepath: '{1}'. (SSA0015)
	ChangingAuditDestinationType = The audit '{0}' currently has destination type '{1}', but expected it to be '{2}'. Re-creating audit '{0}' on server {3} instance '{4}'. (SSA0016)
    CreateFolder = Creating folder {0}. (SSA0017)
    ImposibleFileCombination = Both MaximumFiles and MaximumRolloverFiles have been defined. This is not a supported configuration. (SSA0018)
    ForceNotEnabled = Unable to re-create the server audit. The server audit needs to be re-created but the configuration has not opt-in to re-create the audit. To opt-in set the parameter Force to $true.
'@
