[ClassVersion("1.0.0.0"), FriendlyName("SqlDatabase")]
class MSFT_SqlDatabase : OMI_BaseResource
{
    [Key, Description("The name of the SQL database.")] String Name;
    [Write, Description("An enumerated value that describes if the database is added (Present) or dropped (Absent). Valid values are 'Present' or 'Absent'. Default Value is 'Present'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key, Description("The host name of the SQL Server to be configured.")] String ServerName;
    [Key, Description("The name of the SQL instance to be configured.")] String InstanceName;
    [Write, Description("The name of the SQL collation to use for the new database. Defaults to server collation.")] String Collation;
};
