[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerLogin")]
class MSFT_xSQLServerLogin : OMI_BaseResource
{
    [Write, Description("An enumerated value that describes if the login exists on the SQL instance.\nPresent {default}  \nAbsent   \n"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key, Description("The name of the SQL login.  If LoginType='WindowsUser' or 'WindowsGroup', this is also the name of the user or group in format DOMAIN\name.")] String Name;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("If LoginType='SqlLogin', a PSCredetial object for the SQL login to be created.")] String LoginCredential;
    [Write, Description("The SQL login type."), ValueMap{"SqlLogin","WindowsUser","WindowsGroup"}, Values{"SqlLogin","WindowsUser","WindowsGroup"}] String LoginType;
    [Write, Description("The SQL Server for the login.")] String SQLServer;
    [Write, Description("The SQL instance for the login.")] String SQLInstanceName;
};
