[ClassVersion("1.0.0.0"), FriendlyName("SqlServiceAccount")]
class DSC_SqlServiceAccount : OMI_BaseResource
{
    [Key, Description("The name of the _SQL Server_ instance to be configured.")] String InstanceName;
    [Key, Description("The service type to be managed for the instance that is specified in parameter **InstanceName**."), ValueMap {"DatabaseEngine","SQLServerAgent","Search","IntegrationServices","AnalysisServices","ReportingServices","SQLServerBrowser","NotificationServices"}, Values {"DatabaseEngine","SQLServerAgent","Search","IntegrationServices","AnalysisServices","ReportingServices","SQLServerBrowser","NotificationServices"}] String ServiceType;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("The service account that should be used when running the _Windows_ service.")] String ServiceAccount;
    [Write, Description("The host name of the _SQL Server_ to be configured. Default value is the current computer name.")] String ServerName;
    [Write, Description("Determines whether the service is automatically restarted when a change to the configuration was needed.")] Boolean RestartService;
    [Write, Description("Forces the service account to be updated. Useful for password changes. This will cause _Set_ to be run on each consecutive run.")] Boolean Force;
    [Read, Description("Returns the service account username for the service.")] String ServiceAccountName;
    [Write, Description("The version number for the service type to be managed for the instance that is specified in parameter **InstanceName**. Mandatory when parameter **ServiceType** is set to `'IntegrationServices'`.")] String VersionNumber;
};
