
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerAlwaysOnService")]
class MSFT_xSQLServerAlwaysOnService : OMI_BaseResource
{
    [Required, Description(HADR is Present (enabled) or Absent (disabled)), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key, Description("The hostname of the SQL Server to be configured")] String SQLServer;
    [Key, Description("Name of the SQL instance to be configured. Default is 'MSSQLSERVER'")] String SQLInstanceName;
    [Write, Description("The length of time, in seconds, to wait for the service to restart. Default is 120 seconds.")] Sint32 RestartTimeout;
};

