[ClassVersion("1.0.0.0"), FriendlyName("SqlTraceFlag")]
class DSC_SqlTraceFlag : OMI_BaseResource
{
    [Write, Description("The host name of the _SQL Server_ to be configured. Default value is the current computer name.")] String ServerName;
    [Key, Description("The name of the _SQL Server_ instance to be configured.")] String InstanceName;
    [Write, Description("An array of trace flags that startup options should have. This parameter will replace all the current trace flags with the specified trace flags.")] Uint32 TraceFlags[];
    [Write, Description("An array of trace flags to be added to the existing trace flags.")] Uint32 TraceFlagsToInclude[];
    [Write, Description("An array of trace flags to be removed from the existing trace flags.")] Uint32 TraceFlagsToExclude[];
    [Write, Description("Specifies that there should be no trace flags set on the instance.")] Boolean ClearAllTraceFlags;
    [Write, Description("Forces a restart of the Database Engine service and dependent services after the desired state is set. Default values is $false.")] Boolean RestartService;
    [Write, Description("The time the resource waits while the sql server services are restarted. Defaults to 120 seconds")] Uint32 RestartTimeout;
};
