name: New command proposal
description: If you have a proposal for a new public command that you think should be added to this module. The new command that is proposed shall be able to be used by a new or existing resource.
title: "NewCommandName: New command proposal"
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please replace `NewCommandName` in the issue title (above) with your proposed command name.

        Thank you for contributing and making this module better!
  - type: textarea
    id: description
    attributes:
      label: Command proposal
      description: Provide information how this command will/should work and how it will help users.
    validations:
      required: true
  - type: textarea
    id: proposedParameters
    attributes:
      label: Proposed parameters
      description: |
        List all the proposed parameters and any parameter sets that the command should have. For each parameter provide a detailed description, the data type, if a default value should be used, and if the property is limited to a set of values.
      value: |
        Parameter | Mandatory | Data type | Description | Default value | Allowed values
        --- | --- | --- | --- | --- | ---
        ParameterName | Yes | String | Detailed description | None | None
    validations:
      required: true
  - type: textarea
    id: considerations
    attributes:
      label: Special considerations or limitations
      description: |
        Provide any considerations or limitations you can think of that a contributor should take in account when coding the proposed command, and or what limitations a user will encounter or should consider when using the proposed command.
    validations:
      required: true
