blank_issues_enabled: false
contact_links:
  - name: "Virtual PowerShell User Group #DSC channel"
    url: https://dsccommunity.org/community/contact/
    about: "To talk to the community and maintainers of DSC Community, please visit the #DSC channel."

