[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerDatabaseDefaultLocations")]
class MSFT_xSQLServerDatabaseDefaultLocations : OMI_BaseResource
{
    [Key, Description("The name of the SQL instance to be configured.")] String SQLInstanceName;
    [Key, Description("The host name of the SQL Server to be configured.")] String SQLServer;
    [Key, Description("The default location type. Valid states are Data, Log, or Backups."), ValueMap{"Data","Log","Backup"}, Values{"Data","Log","Backup"}] String DefaultLocationType;
    [Required, Description("The full path to the desired default location.")] String DefaultLocationPath;
    [Write, Description("If set to $true then SQL Server and dependent services will be restarted if a change to the default location is made.  The defaul value is $false.")] Boolean RestartService;
};
