[ClassVersion("1.0.0.0"), FriendlyName("xSQLAOGroupJoin")]
class MSFT_xSQLAOGroupJoin : OMI_BaseResource
{
    [Key, Description("If the replica should be joined ('Present') to the Availability Group or not joined ('Absent') to the Availability Group."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key, Description("The name Availability Group to join.")] String AvailabilityGroupName;
    [Write, Description("Name of the SQL server to be configured.")] String SQLServer;
    [Write, Description("Name of the SQL instance to be configured.")] String SQLInstanceName;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("Credential to be used to Grant Permissions in SQL.")] String SetupCredential;
};

