[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerMemory")]
class MSFT_xSQLServerMemory : OMI_BaseResource
{
    [Key, Description("The name of the SQL instance to be configured.")] String SQLInstanceName;
    [Required, Description("The host name of the SQL Server to be configured.")] String SQLServer;
    [Write, Description("An enumerated value that describes if Min and Max memory is configured"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Flag to Dynamically allocate SQL memory based on Best Practices")] Boolean DynamicAlloc;
    [Write, Description("Minimum amount of memory, in MB, in the buffer pool used by the instance of SQL Server")] Sint32 MinMemory;
    [Write, Description("Maximum amount of memory, in MB, in the buffer pool used by the instance of SQL Server")] Sint32 MaxMemory;
};
