[ClassVersion("1.0.0.0"), FriendlyName("SqlConfiguration")]
class DSC_SqlConfiguration : OMI_BaseResource
{
    [Key, Description("Name of the _SQL Server_ instance to be configured.")] String InstanceName;
    [Key, Description("The name of the _SQL Server Database Engine_ instance configuration option. For all possible values reference the article [Server Configuration Options (SQL Server)](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/server-configuration-options-sql-server) or run `sp_configure`.")] String OptionName;
    [Required, Description("The desired value of the configuration option.")] SInt32 OptionValue;
    [Write, Description("The hostname of the _SQL Server_ to be configured. Default value is the current computer name.")] String ServerName;
    [Write, Description("Determines whether the instance should be restarted after updating the configuration option.")] Boolean RestartService;
    [Write, Description("The length of time, in seconds, to wait for the service to restart. Default is `120` seconds.")] UInt32 RestartTimeout;
};
