[ClassVersion("1.0.0.0"), FriendlyName("SqlServiceAccount")]
class MSFT_SqlServiceAccount : OMI_BaseResource
{
    [Key, Description("Hostname of the SQL Server.")] String ServerName;
    [Key, Description("Name of the SQL instance.")] String InstanceName;
    [Key, Description("Type of service being managed."), ValueMap {"DatabaseEngine","SQLServerAgent","Search","IntegrationServices","AnalysisServices","ReportingServices","SQLServerBrowser","NotificationServices"}, Values {"DatabaseEngine","SQLServerAgent","Search","IntegrationServices","AnalysisServices","ReportingServices","SQLServerBrowser","NotificationServices"}] String ServiceType;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("The service account that should be used when running the service.")] String ServiceAccount;
    [Write, Description("Determines whether the service is automatically restarted when a change to the configuration was needed.")] Boolean RestartService;
    [Write, Description("Forces the service account to be updated. Useful for password changes.")] Boolean Force;
    [Read, Description("Returns the service account username for the service.")] String ServiceAccountName;
};
