# Swedish localized resources for SqlSetup

ConvertFrom-StringData @'
    UsingPath = Använder sökväg '{0}'.
    EvaluateReplicationFeature = Letar efter funktionen Replication.
    ReplicationFeatureFound = Replication funktionen hittad.
    ReplicationFeatureNotFound = Replication funktionen hittades inte.
    EvaluateDataQualityClientFeature = Letar efter Data Quality Client funktionen ({0}).
    DataQualityClientFeatureFound = Data Quality Client funktionen hittad.
    DataQualityClientFeatureNotFound = Data Quality Client funktionen hittades inte.
    EvaluateDataQualityServicesFeature = Letar efter Data Services Client funktionen.
    DataQualityServicesFeatureFound = Data Quality Services funktionen hittad.
    DataQualityServicesFeatureNotFound = Data Quality Services funktionen hittades inte.
    ClusterInstanceFound = Klustrad instans hittad.
    ClusterInstanceNotFound = Klustrad instans hittades inte.
    FailoverClusterResourceFound = En SQL Server klusterresurs hittad.
    FailoverClusterResourceNotFound = Kunde inte hitta en SQL Server klusteresurs för instans {0}.
    EvaluateDocumentationComponentsFeature = Letar efter Documentation Components funktionen ({0}).
    DocumentationComponentsFeatureFound = Documentation Components funktionen hittad.
    DocumentationComponentsFeatureNotFound = Documentation Components funktionen hittades inte.
    EvaluateDatabaseEngineFeature = Letar efter Database Engine funktionen.
    DatabaseEngineFeatureFound = Database Engine funktionen hittad.
    DatabaseEngineFeatureNotFound = Database Engine funktionen hittades inte.
    EvaluateFullTextFeature = Letar efter Full-text funktionen.
    FullTextFeatureFound = Full-text funktionen hittad.
    FullTextFeatureNotFound = Full-text funktionen hittades inte.
    EvaluateReportingServicesFeature = Letar efter Reporting Services funktionen.
    ReportingServicesFeatureFound = Reporting Services funktionen hittad.
    ReportingServicesFeatureNotFound = Reporting Services funktionen hittades inte.
    EvaluateAnalysisServicesFeature = Letar efter Analysis Services funktionen.
    AnalysisServicesFeatureFound = Analysis Services funktionen hittad.
    AnalysisServicesFeatureNotFound = Analysis Services funktionen hittades inte.
    EvaluateIntegrationServicesFeature = Letar efter Integration Services funktionen.
    IntegrationServicesFeatureFound = Integration Services funktionen hittad.
    IntegrationServicesFeatureNotFound = Integration Services funktionen hittades inte.
    ClientConnectivityToolsFeatureFound = Client Connectivity Tools funktionen hittad.
    ClientConnectivityToolsFeatureNotFound = Client Connectivity Tools funktionen hittades inte.
    ClientConnectivityBackwardsCompatibilityToolsFeatureFound = Client Connectivity Backwards Compatibility Tools funktionen hittad.
    ClientConnectivityBackwardsCompatibilityToolsFeatureNotFound = Client Connectivity Backwards Compatibility Tools funktionen hittades inte.
    ClientToolsSdkFeatureFound = Client Tools SDK funktionen hittad.
    ClientToolsSdkFeatureNotFound = Client Tools SDK funktionen hittades inte.
    FeatureNotSupported = '{0}' är inte ett giltigt värde för egenskapen 'FEATURES'. Titta i hjälpdokumentationen för SQL Server för mer information.
    PathRequireClusterDriveFound = Hittade tilldelad parameter '{0}'. Adderar sökväg '{1}' till listan av sökvägar som kräver en klustrad enhet.
    FailoverClusterDiskMappingError = Kunde inte koppla den specifika sökvägen till en giltig klusterlagring. Enheter kopplade: {0}.
    FailoverClusterIPAddressNotValid = Kunde inte koppla den specifika IP-adressen, eller IP-adresser, till ett giltigt klusternätverk.
    AddingFirstSystemAdministratorSqlServer = Adderar användaren '{0}' från parametern 'PsDscRunAsCredential' som det första systemadminstratörskontot för SQL Server.
    AddingFirstSystemAdministratorAnalysisServices = Adderar användaren '{0}' från parametern 'PsDscRunAsCredential' som det första systemadminstratörskontot för Analysis Services.
    SetupArguments = Startar installationen med följande argument: {0}
    SetupExitMessage = Installationen avslutades med felkod '{0}'.
    SetupSuccessful = Installationen lyckades.
    SetupSuccessfulRebootRequired = Installationen lyckades, men en omstart krävs.
    SetupFailed = Vänligen titta i loggfilen 'Summary.txt' i sökvägen 'Setup Bootstrap\\Log'.
    Reboot = Startar om målnod.
    SuppressReboot = Förhindrar omstart av målnod.
    TestFailedAfterSet = Funktionen Test-TargetResource returnerade falskt när funktionen Set-TargetResource verifierade önskad konfiguration. Detta indikerar att funktionen Set-TargetResource inte på ett korrekt sätt kunde sätta önskad konfiguration, eller att funktionen Test-TargetResource inte utvärderar önskad konfiguration på korrekt sätt. Vänligen titta efter rapporterade fel från setup.exe i SQL Server installationsloggarna, för information hur man gör det se artikeln https://docs.microsoft.com/en-us/sql/database-engine/install-windows/view-and-read-sql-server-setup-log-files (View and Read SQL Server Setup Log Files).
    FeaturesFound = Funktioner funna: {0}
    NoFeaturesFound = Inga funktioner är installerad.
    UnableToFindFeature = Kunde inte hitta funktion '{0}' bland som installerade funktionerna: '{1}'.
    EvaluatingClusterParameters = Klustrad installation, kontrollerar parametrar.
    ClusterParameterIsNotInDesiredState = {0} '{1}' är inte i önskat läge för detta kluster.
    EvaluateMasterDataServicesFeature = Letar efter Master Data Services (MDS) funktion ({0}).
    MasterDataServicesFeatureFound = Master Data Services (MDS) funktionen hittad.
    MasterDataServicesFeatureNotFound = Master Data Services (MDS) funktionen hittades inte.
    FeatureAlreadyInstalled = Funktionen '{0}' är redan installerad så den kommer inte bli installerad igen.
    FeatureFlag = Använder tilläggsflagga '{0}'
    DifferentMajorVersion = The instance '{0}' has the wrong major version. The major version is '{1}', but expected version '{2}'.
    ParameterSqlVersionNotAllowedForSetupActionUpgrade = The parameter SqlVersion is not allowed to be specified when using the setup action Upgrade.
'@
