name: Code analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pssa:
    name: PSScriptAnalyzer
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: PowerShell Module Cache
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: PSScriptAnalyzer::, ConvertToSARIF::
          allow-prerelease: false
          updatable: true
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.0
        with:
          path: ./source
          recurse: true
          output: results.sarif
          settings: ./.vscode/analyzersettings.psd1
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
