name: Code analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pssa:
    name: PSScriptAnalyzer
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: PowerShell Module Cache
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: "PSScriptAnalyzer::,ConvertToSARIF::"
          updatable: true
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          # Only get the analyzer rule modules.
          New-Item -Path './output/RequiredModules' -ItemType Directory -Force | Out-Null
          Save-Module -Name 'DscResource.AnalyzerRules' -Path './output/RequiredM*odules' -Force
          Save-Module -Name 'Indented.ScriptAnalyzerRules' -Path './output/RequiredModules' -Force

          Add-Type -Path './tests/Unit/Stubs/SMO.cs'

          Import-Module ConvertToSARIF -Force

          Get-ChildItem -Path './source/' -Recurse -Include @('*.psm1', '*.ps1') -File |
            Invoke-ScriptAnalyzer -Settings './.vscode/analyzersettings.psd1' |
            ConvertTo-SARIF -FilePath 'results.sarif'
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
