[ClassVersion("1.0.0.0"), FriendlyName("SqlServerAuditSpecification")]
class MSFT_SqlServerAuditSpecification : OMI_BaseResource
{
    [Key, Description("Specifies the host name of the SQL Server on which the instance exist.")] String ServerName;
    [Key, Description("Specifies the SQL instance in which the Audit exist.")] String InstanceName;
    [Key, Description("Specifies the name of the SQL audit specification to be added or removed.")] String Name;
    [Write, Description("Specifies if the audit specification should be enabled. Defaults to $false")] Boolean Enabled;
    [Write, Description("Specifies the audit to be used as storage.")] String AuditName;
    [Write, Description("Specifies if this should be audited.")] Boolean ApplicationRoleChangePasswordGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean AuditChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean BackupRestoreGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean BrokerLoginGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabaseChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabaseLogoutGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabaseMirroringLoginGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabaseObjectAccessGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabaseObjectChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabaseObjectOwnershipChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabaseObjectPermissionChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabaseOperationGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabaseOwnershipChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabasePermissionChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabasePrincipalChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabasePrincipalImpersonationGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DatabaseRoleMemberChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean DbccGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean FailedDatabaseAuthenticationGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean FailedLoginGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean FulltextGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean LoginChangePasswordGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean LogoutGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean SchemaObjectAccessGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean SchemaObjectChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean SchemaObjectOwnershipChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean SchemaObjectPermissionChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean ServerObjectChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean ServerObjectOwnershipChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean ServerObjectPermissionChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean ServerOperationGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean ServerPermissionChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean ServerPrincipalChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean ServerPrincipalImpersonationGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean ServerRoleMemberChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean ServerStateChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean SuccessfulDatabaseAuthenticationGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean SuccessfulLoginGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean TraceChangeGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean UserChangePasswordGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean UserDefinedAuditGroup;
    [Write, Description("Specifies if this should be audited.")] Boolean TransactionGroup;
    [Write, Description("Specifies if the audit should be present or absent. If 'Present' then the audit will be added to the server and, if needed, the audit will be updated. If 'Absent' then the audit will be removed from the server. Defaults to 'Present'."), ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
    [Write, Description("Specifies if it is allowed to re-create the server audit when the DestinationType changes. Defaults to $false not allowing server audits to be re-created.")] Boolean Force;
};
